run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  tests: false

output:
  print-issued-lines: false
  print-linter-name: true
  uniq-by-line: false
  path-prefix: ""
  sort-results: true

linters:
  disable-all: true

  enable:
    # bugs/error
    - staticcheck
    - revive
    - govet

    # performance
    - gocritic
    - prealloc

    # style, formatting
    - stylecheck
    - gofmt

linters-settings:
  gofmt:
    # Apply the rewrite rules to the source before reformatting.
    # https://pkg.go.dev/cmd/gofmt
    # Default: []
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'
  staticcheck:
    go: "1.22"
    # STxxxx checks in https://staticcheck.io/docs/configuration/options/#checks
    # Default: ["*"]
    checks: [ "all","-U1000", "-ST1003","-SA4006"]
  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#var-naming
      - name: var-naming
        severity: warning
        disabled: true
